### ISSUE TITLE
Windows compatible?

### ISSUE THREAD

**Issue by al-sabr** [prologic/bitcask#145]
Greetings to all!

My question is simple :D

**Comment by tdakkota** [comment]
> Greetings to all!
> 
> My question is simple :D

@gdeverlaInt 
I used Bitcask on Windows, so I had no problem.
Also, Bitcask uses [flock](https://github.com/gofrs/flock), it is Windows-compatible.

**Comment by prologic** [comment]
@tdakkota is right. Bitcask _should_ work on Windows. The problem is none of the developers/contributions thus far have Windows machines to do dev/testing on. There is a test suite that also runs in CI on Windows (_bar a few disabled tests that are known to fail_); but other than this things should work fine!

Please open any specific issues/nugs/features if you have any :)
