### ISSUE TITLE
Concurrent Merge() with other operations causes data races and potentially data loss

### ISSUE THREAD

**Issue by prologic** [prologic/bitcask#187]
This is an FYI.

This is a **bug** or a **known limitation**.

For the time being, _try to avoid doing this_.

**Comment by prologic** [comment]
Affects (_so far_) the [jointwt/twtxt](https://github.com/jointwt/twtxt) backend.

**Comment by yashschandra** [comment]
How about mark and sweep approach?
Step 1 - merge triggered, close current datafile and mark existing datafiles
Step 2 - start new datafile for new writes
Step 3 - start merge operation
Step 4 - after merge is complete, remove only those datafiles that were marked
Step 5 - rebuild index

downside I see is datafile names will not be in contiguous order (since merge can potentially decrease total number of datafiles needed)

**Comment by prologic** [comment]
> How about mark and sweep approach?
> Step 1 - merge triggered, close current datafile and mark existing datafiles
> Step 2 - start new datafile for new writes
> Step 3 - start merge operation
> Step 4 - after merge is complete, remove only those datafiles that were marked
> Step 5 - rebuild index

I like this idea... Can you put a PR up for this to try it out? The main concern I have really at the moment is that some of the mutex locking is a "bit off" and could do with some careful rework.

> downside I see is datafile names will not be in contiguous order (since merge can potentially decrease total number of datafiles needed)

This really isn't a downside per se 😀

**Comment by yashschandra** [comment]
#191 should resolve race condition between merge and put

**Comment by yashschandra** [comment]
Also thinking if it makes sense to allow only 1 merge operation at a time (there is no need to run multiple merge concurrently). What do you think?

**Comment by prologic** [comment]
Agreed

**Comment by yashschandra** [comment]
Will update the pr

**Comment by yashschandra** [comment]
> The main concern I have really at the moment is that some of the mutex locking is a "bit off" and could do with some careful rework.

Found an issue with using _Merge_ concurrently with _Put_ due to locking. Consider scenario -
1. _Merge_ triggered
2. _Merge_ calls _Fold_, **read** lock taken
3. _Put_ called concurrently, waits for taking **write** lock
4. _Fold_ calls _Get_, waits for taking **read** lock
Now we a have deadlock situation.

Reason - As per documentation of RWMutex: _a blocked Lock call excludes new readers from acquiring the lock_.

**Comment by prologic** [comment]
Can we close this?

**Comment by yashschandra** [comment]
> Affects (so far) the jointwt/twtxt backend.

Can you check some more if twtxt backend is not facing this issue?

**Comment by prologic** [comment]
> Can you check some more if twtxt backend is not facing this issue?

Yes I will add it back to twtxt backend and test for a week to see if we have the same problems.

**Comment by yashschandra** [comment]
@prologic do you think we have enough tested it that we can close?

**Comment by prologic** [comment]
Yea let's close this
