### ISSUE TITLE
Version on-disk database

### ISSUE THREAD

**Issue by awnumar** [prologic/bitcask#59]
A version number or identifier could be stored in the database to aid the export tool, since it would need to understand every historical format that the on-disk store used.

Somewhat related to #54 as [other stores](https://github.com/dgraph-io/badger#choosing-a-version) use custom versioning rules to handle the different levels of compatibility, which is not very pretty.

**Comment by prologic** [comment]
I would imagine this adds a fair bit of complexity? Is there a way we can manage this? You are right in that right now the `bitcask export` tool only understand the on-disk format for the version it was compiled for at the time.

So for example; to upgrade to the new on-disk format that #49 / #52 introduced; you would need to go grab the [v0.3.2](https://github.com/prologic/bitcask/releases/tag/v0.3.2) `bitcask` binary and use _that_ to do the export.

Then you can use the later version to do an import.

So this adds a bit of burden to the user I guess.

**Comment by prologic** [comment]
We could keep code for handling the last N on-disk formats, say last 3? The question then is do we keep the last one we just changed? I say no because it was a pretty heavy dependency to drag around (`protobuf` and friends) and I'd rather just see that format just die a quick death :) -- But going forward we certainly can! (_if it ever changes at all?_)

**Comment by awnumar** [comment]
Ah true, I hadn't considered that was possible. I agree that's a good enough solution to be honest.

**Comment by prologic** [comment]
Oh well we got out of writing a tonne of code then didn't we 😂
