### ISSUE TITLE
undefined: proto.InternalMessageInfo

### ISSUE THREAD

**Issue by amit-siddhu** [prologic/bitcask#6]
```
go get github.com/prologic/bitcask                                    
# github.com/prologic/bitcask/internal/proto
go/src/github.com/prologic/bitcask/internal/proto/entry.pb.go:53:27: undefined: proto.InternalMessageInfo
```

**Comment by prologic** [comment]
Hi @amit-siddhu Thanks for trying this library/tool out! Before we close this; I'd like to understand how you were lead to this! I have clearly not documented something correctly here. So I'm keen to address that.

The other thing is I've often seen some proejcts commit the generated `*.pb.go` files so that the library is `go get`'able as-is without any special things you need to do -- Need to also consider that.

Let me know what your thoughts are :)

**Comment by prologic** [comment]
For any lack of response; I will just do what I *think* is right.

* [ ] Address lack of documentation around the need to `go generate` (*which there exists a `Makefile` target for `make generate`*)
* [ ] Commit the generated `*_pb.go` files so the library is `go get`-able without any special handling.

**Comment by prologic** [comment]
Turns out I was missing a dependency in `go.mod` 🤦‍♂️
